### ISSUE TITLE
Unsupported TLD query is flawed

### ISSUE THREAD

**Issue by domainbf** [HoundSec/flask_whois#5]
If the tld cannot be found, it will directly jump to https://whois.houndsec.net/lookup, and the page will display: Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Itsmmdoha** [comment]
Thanks for reporting this! Could you let us know which TLD or domain you tried and how you encountered the issue? This will help us reproduce and fix the problem.

**Comment by whois-ls** [comment]
Hello, the program responds well to common domain names, but for some domain names of CCtld, the query cannot be found, so the displayed page will crash. You can try to query the domain name nic.bn and you can see the problem.
